### PR TITLE
lima-init.service: Run in network namespace

### LINKED ISSUE #32: lima-init should be run in network namespace
https://github.com/rancher-sandbox/rancher-desktop-opensuse/blob/04130ae51aa8ec6c078f6da728a11a7220307908/root/usr/local/lib/systemd/system/lima-init.service is currently not run inside the network namespace; this causes things like downloading k3s to fail.

It should get an unit drop-in to set it, like https://github.com/rancher-sandbox/rancher-desktop-opensuse/blob/04130ae51aa8ec6c078f6da728a11a7220307908/root/usr/local/lib/systemd/system/containerd.service.d/network-namespace.conf does (by running the command under `wsl-exec`).

The bulk of the task here is to check that things work correctly.

### PR DESCRIPTION
**Pull request by mook-as**
We did not enable lima-init on WSL; do so, so that we can run any system-supplied provisioning scripts.  Note that we expect user script to be run under `local.service` (which is currently not implemented).

Note that we do not run `rd-init.service` on WSL.

Fixes #32

### CODE REVIEW

File: config.sh [hunk 1]
```diff
@@ -113,6 +113,10 @@ fi
 # WSL-specific fixes
 #--------------------------------------
 if [[ ${kiwi_profiles:-} =~ wsl ]]; then
+    # No rd-init.service or ci-data mount on WSL
+    rm -f /usr/local/lib/systemd/system/lima-init.service.d/requires-cidata.conf
```
Comment (Nino-K) [inline config.sh:117]: This removes the `/mnt/lima-cidata` mount requirement for WSL, but `network-namespace.conf` still overrides ExecStart to run `/mnt/lima-cidata/boot.sh`. If WSL does not have ci-data, this seems like it could make `lima-init.service` fail at startup. Should the WSL override point to a WSL-specific script instead, or should the cidata requirement remain when `network-namespace.conf` is active?

File: config.sh [hunk 2]
```diff
@@ -88,6 +88,7 @@ chmod 0755 /usr/local/libexec/udhcpc/*.script
 # Enable services
 #--------------------------------------
 systemctl enable sshd
+systemctl enable lima-init.service
```
Comment (Nino-K) [inline config.sh:91]: I guess it's intentional to enable lima-init.service unconditionally for every image profile.

File: config.sh (hunk 1 above)
Comment (mook-as) [reply config.sh:117]: On windows, cidata is actually a symlink to the inside of the drvfs mount (i.e. it's just directly accessing the host filesystem), so it's fine.

File: config.sh (hunk 2 above)
Comment (mook-as) [reply config.sh:91]: Yes, because otherwise we won't get the init scripts (this was initially raised because there was an issue with the k3s install, or something along those lines; the report to me was sort of vague).

**Review by Nino-K — APPROVED** [review]
